### ISSUE TITLE
Figure out why Prometheus isn't reconciling Flux PodMonitor

### ISSUE THREAD

**Issue by glitchcrab** [a7d-corp/a7d-corp#40]
https://github.com/a7d-corp/homelab-clusters-addons/blob/main/flux/apps/base/kube-prometheus-stack/configs/podmonitor-flux-system.yaml

**Comment by glitchcrab** [comment]
prom values:

```
  podMonitorNamespaceSelector:
    matchLabels:
      kustomize.toolkit.fluxcd.io/namespace: cluster-room101-a7d-mc
  podMonitorSelectorNilUsesHelmValues: false
```
